version: '3.9'

services:
  backend:
    build: .
    command: python parser.py
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12
    env_file:
      - ./.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432



volumes:
  postgres_data: